### ISSUE TITLE
Bug Report: Regression in latest version - Torrents stuck at 100% "downloading" state

### ISSUE THREAD

**Issue by jamcalli** [sirrobot01/decypharr#70]
**Environment:**
- Previously working: ghcr.io/sirrobot01/decypharr:beta
- Broken after upgrade: cy01/blackhole:latest
- Config: `folder_naming: "filename"`, `use_webdav: true`
- Setup: Decypharr → Rclone WebDAV mount → RealDebrid

**Issue:**
After upgrading from beta to latest, torrents remain stuck in "downloading" state at 100% progress, preventing symlink creation and Arr imports. This worked correctly in the beta version. This is probably something I have goofed, or overlooked some new setting, but thought I would check. 

**Current behavior (latest version):**
1. Files successfully download to RealDebrid
2. Decypharr creates empty directories in `/mnt/symlinks/`
3. Torrents show `"progress": 1` but `"state": "downloading"`
4. No symlinks are created
5. Arrs never receive completion notification

**Previous behavior (beta version):**
All of the above worked correctly - torrents would complete and symlinks would be created.

**API response showing the issue:**
```json
{
  "name": "the.secret.garden.2020.hdr.2160p.web.h265-huzzah.mkv",
  "progress": 1,
  "state": "downloading",
  "completed": 11353719061,
  "size": 11353719061
}
```

**Docker Compose Configuration:**
```yaml
services:
 decypharr:
   image: cy01/blackhole:latest
   container_name: decypharr
   user: "1000:1000"
   volumes:
     - /mnt/:/mnt
     - ./config:/app
   environment:
     - PUID=1000
     - PGID=1000
     - UMASK=002
   ports:
     - "8282:8282/tcp"
   restart: unless-stopped

 rclone:
   image: rclone/rclone:latest
   container_name: rclone
   restart: unless-stopped
   environment:
     TZ: America/Los_Angeles
     PUID: 1000
     PGID: 1000
   ports:
     - 5572:5572
   volumes:
     - /mnt/remote/realdebrid:/data:rshared
     - ./rclone.conf:/config/rclone/rclone.conf
     - /mnt:/mnt
   cap_add:
     - SYS_ADMIN
   security_opt:
     - apparmor:unconfined
   devices:
     - /dev/fuse:/dev/fuse:rwm
   depends_on:
     decypharr:
       condition: service_healthy
       restart: true
   command: "mount decypharr: /data --allow-non-empty --allow-other --uid=1000 --gid=1000 --umask=002 --dir-cache-time 10s --rc --rc-addr :5572 --rc-no-auth"
```

**config.json (sanitized):**
```json
{
 "url_base": "/",
 "port": "8282",
 "log_level": "debug",
 "debrids": [
   {
     "name": "realdebrid",
     "api_key": "REDACTED",
     "download_api_keys": [
       "REDACTED"
     ],
     "folder": "/mnt/remote/realdebrid/__all__/",
     "rate_limit": "250/minute",
     "use_webdav": true,
     "torrents_refresh_interval": "15s",
     "download_links_refresh_interval": "40m",
     "workers": 50,
     "auto_expire_links_after": "3d",
     "folder_naming": "filename",
     "rc_url": "http://rclone:5572",
     "rc_refresh_dirs": "__all__"
   }
 ],
 "qbittorrent": {
   "download_folder": "/mnt/symlinks/",
   "refresh_interval": 5
 },
 "arrs": [
   {
     "name": "radarr",
     "host": "http://REDACTED:7878",
     "token": "REDACTED",
     "cleanup": true,
     "download_uncached": false
   },
   {
     "name": "tv-sonarr",
     "host": "http://REDACTED:8989",
     "token": "REDACTED",
     "cleanup": true,
     "download_uncached": false
   }
 ],
 "repair": {
   "interval": "12h",
   "use_webdav": true
 },
 "webdav": {},
 "allowed_file_types": [
   "3gp",
   "ac3",
   "aiff",
   "alac",
   "amr",
   "ape",
   "asf",
   "asx",
   "avc",
   "avi",
   "bin",
   "bivx",
   "dat",
   "divx",
   "dts",
   "dv",
   "dvr-ms",
   "flac",
   "fli",
   "flv",
   "ifo",
   "img",
   "iso",
   "m2ts'",
   "m2v",
   "m3u",
   "m4a",
   "m4p",
   "m4v",
   "mid",
   "midi",
   "mk3d",
   "mka",
   "mkv",
   "mov",
   "mp2",
   "mp3",
   "mp4",
   "mpa",
   "mpeg",
   "mpg",
   "nrg",
   "nsv",
   "nuv",
   "ogg",
   "ogm",
   "ogv",
   "pva",
   "qt",
   "ra",
   "rm",
   "rmvb",
   "strm",
   "svq3",
   "ts",
   "ty",
   "viv",
   "vob",
   "voc",
   "vp3",
   "wav",
   "webm",
   "wma",
   "wmv",
   "wpl",
   "wtv",
   "wv",
   "xvid"
 ],
 "discord_webhook_url": "REDACTED"
}
```
