### ISSUE TITLE
Cannot Save Setting: Permission Denied

### ISSUE THREAD

**Issue by naby-dev** [sirrobot01/decypharr#78]
![Image](https://github.com/user-attachments/assets/53b10030-8d96-4286-98e0-af47e7a95ed0)

```
decypharr:
    image: cy01/blackhole:latest
    container_name: decypharr
    ports:
      - "8282:8282"
    volumes:
      - ${DOCKER_APPDATA}/decypharr/config.json:/app/config.json
      - type: bind
        source: /mnt
        target: /mnt
        bind:
          propagation: rslave
    networks:
      - mediarr-network
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=002
    user: "1000:1000"
    restart: unless-stopped
```

where DOCKER_APPDATA=/opt/appdata.

Any idea? I suspect I need to give my container sudo access.
